# Copyright (C) 2018  Ratheesh <ratheeshreddy@gmail.com>
# Author: Ratheesh S
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# servers=[
#   {
#     :hostname => "ubuntu1404",
#     # :ip => "192.168.100.10",
#     :box => "ubuntu/trusty64",
#     :ram => 1024,
#     :cpu => 2,
#     :provision_path => "provision.sh"
#   },
#   {
#     :hostname => "ubuntu1604",
#     # :ip => "192.168.100.11",
#     :box => "ubuntu/xenial64",
#     :ram => 1024,
#     :cpu => 2,
#     :provision_path => "provision.sh"
#   },
#   {
#     :hostname => "ubuntu1804",
#     # :ip => "192.168.100.12",
#     :box => "ubuntu/bionic64",
#     :ram => 1024,
#     :cpu => 2,
#     :provision_path => "provision.sh"
#   }
# ]
# Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#     servers.each do |machine|
#         config.vm.define machine[:hostname] do |node|
#             node.vm.box = machine[:box]
#             node.vm.hostname = machine[:hostname]
#             # node.vm.network "private_network", ip: machine[:ip]
#             node.vm.provision :shell, path: machine[:provision_path]
#             node.vm.provider "virtualbox" do |vb|
#                 vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
#                 vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#                 vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
#             end
#         end
#     end
# end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # common settings
    # config.vm.synced_folder "src/", "/srv/website"
    config.vm.provision :shell, path: "provision.sh"

    Vagrant::Config.run do |cfg|
        cfg.ssh.port            = 22
        cfg.ssh.compression     = true
        cfg.ssh.forward_agent   = true
        cfg.ssh.verify_host_key :never
        cfg.ssh.forward_agent   = true
    end

    # Ubuntu 14.04
    config.vm.define "ubuntu1404", primary: true do |trusty|
        trusty.vm.box = "ubuntu/trusty64"
        trusty.vm.hostname="ubuntu1404"
        trusty.vm.provider "ubuntu1404" do |vb|
            vb.customize ["modifyvm", :id, "--memory", 1024]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        end
    end

    # Ubuntu 16.04
    config.vm.define "ubuntu1604",autostart:false do |xenial|
        xenial.vm.box = "ubuntu/xenial64"
        xenial.vm.hostname="ubuntu1604"
        xenial.vm.provider "ubuntu1604" do |vb|
            vb.customize ["modifyvm", :id, "--memory", 1024]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        end
    end

    # Ubuntu 18.04
    config.vm.define "ubuntu1804",autostart:false do |bionic|
        bionic.vm.box = "ubuntu/bionic64"
        bionic.vm.hostname="ubuntu1804"
        bionic.vm.provider "ubuntu1804" do |vb|
            vb.customize ["modifyvm", :id, "--memory", 1024]
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        end
    end

end

# Template to create a single vagrant box
# Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#   config.vm.define "vbox", primary: true do |vbox|
#     vbox.vm.box = "ubunt/xenial64"
#     vbox.vm.hostname="hostname"
#     vbox.vm.provision :shell, path: "provision.sh"
#     vbox.vm.provider "virtualbox" do |vb|
#       vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
#         vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#         vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
#       end
#   end
# end

# End of File
#  vim: set ft=ruby ff=unix ts=8 sw=4 expandtab:
