# Copyright (C) 2018  Ratheesh <ratheeshreddy@gmail.com>
# Author: Ratheesh S
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

servers=[
  {
    :hostname => "ubuntu1404",
    # :ip => "192.168.100.10",
    :box => "ubuntu/trusty64",
    :ram => 1024,
    :cpu => 2,
    :provision_path => "provision.sh"
  },
  {
    :hostname => "ubuntu1604",
    # :ip => "192.168.100.11",
    :box => "ubuntu/xenial64",
    :ram => 1024,
    :cpu => 2,
    :provision_path => "provision.sh"
  },
  {
    :hostname => "ubuntu1804",
    # :ip => "192.168.100.12",
    :box => "ubuntu/bionic64",
    :ram => 1024,
    :cpu => 2,
    :provision_path => "provision.sh"
  }
]
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            # node.vm.network "private_network", ip: machine[:ip]
	    node.vm.provision :shell, path: machine[:provision_path]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            end
        end
    end
end

# Template to create a single vagrant box
# Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#   config.vm.define "vbox" do |vbox|
#     vbox.vm.box = "ubunt/xenial64"
#     vbox.vm.hostname="hostname"
#     vbox.vm.provision :shell, path: "provision.sh"
#     vbox.vm.provider "virtualbox" do |vb|
#       vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
#         vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#         vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
#       end
#   end
# end

# End of File
