ZSHA_BASE=$HOME/.zsh-antigen/
source $ZSHA_BASE/antigen/antigen.zsh

#antigen-use oh-my-zsh
antigen-use prezto

if [ "$OSTYPE"="darwin11.0" ]; then
  antigen-bundle osx
fi

antigen bundles <<EOB
    sorin-ionescu/prezto modules/environment
    sorin-ionescu/prezto modules/git
    sorin-ionescu/prezto modules/terminal
    sorin-ionescu/prezto modules/spectrum
    sorin-ionescu/prezto modules/utility
    sorin-ionescu/prezto modules/dpkg
    sorin-ionescu/prezto modules/command-not-found
    sorin-ionescu/prezto modules/completion

    robbyrussell/oh-my-zsh plugins/colored-man

    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-history-substring-search
    Tarrasch/zsh-bd
    jocelynmallon/zshmarks
    knu/zsh-manydots-magic
    extract
    zsh-users/zsh-completions
EOB
# zsh-users/zaw

antigen-apply

# custom settings

ZDOTDIR=$HOME

path=(
    $HOME/bin
    $HOME/.local/bin
    $HOME/.autojump/bin
    # /usr/local/share/perl5/auto/share/dist/Cope # colorize terminal programs
    /usr/local/share/perl/5.18.2/auto/share/dist/Cope # ubuntu systems
    /usr/local/{bin,sbin}
    /{bin,sbin}
    /usr/{bin,sbin}
    $path
)

# Some basic settings
unsetopt beep
setopt shwordsplit
setopt append_history
setopt hist_ignore_dups
setopt shwordsplit	     # make sure that $arm works fine
unsetopt correct_all	     # do not correct all automatically
setopt nobgnice              # run bg jobs at full speed
setopt complete_in_word      # allow tab completion in the middle of a word
unsetopt flowcontrol	     # ctr-s/q has not effect now (Thanx!!!)

zstyle ":completion:*:commands" rehash 1

autoload -U compinit && compinit
autoload -U colors && colors
zmodload -i zsh/complist

HISTSIZE=5000 # session history size
SAVEHIST=1000 # saved history
HISTFILE=$HOME/.zshistory # history file
setopt append_history           # append
setopt hist_ignore_all_dups     # no duplicate
unsetopt hist_ignore_space      # ignore space prefixed commands
setopt hist_reduce_blanks       # trim blanks
setopt hist_verify              # show before executing history commands
setopt inc_append_history       # add commands as they are typed, don't wait until shell exit 
setopt share_history            # share hist between sessions
setopt bang_hist                # !keyword
setopt MULTIOS
unsetopt rm_star_silent         # ask for confirmation for `rm *' or `rm path/*'
unsetopt hup                    # no hup signal at shell exit
unsetopt bg_nice                # no lower prio for background jobs
setopt auto_remove_slash        # self explicit

# zsh completion configuration
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'   # ignore case
zstyle ':completion:*' menu select=2                        # menu if nb items > 2
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}       # colorz !
zstyle ':completion:*::::' completer _expand _complete _ignored _approximate # list of completers to use

zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format $'\e[00;34m%d'
zstyle ':completion:*:messages' format $'\e[00;31m%d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*:manuals' separate-sections true

zstyle ':completion:*:processes' command 'ps -au$USER'
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:kill:*' force-list always
zstyle ':completion:*:*:kill:*:processes' list-colors "=(#b) #([0-9]#)*=29=34"
zstyle ':completion:*:*:killall:*' menu yes select
zstyle ':completion:*:killall:*' force-list always

zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
  'r:[[:ascii:]]||[[:ascii:]]=** r:|=* m:{a-z\-}={A-Z\_}'

# history substring search
bindkey -M emacs "^p" history-substring-search-up
bindkey -M emacs "^n" history-substring-search-down
bindkey -M emacs '^r' history-incremental-search-backward

# pick item but stay in menu
bindkey -M menuselect "+" accept-and-menu-complete

# aliases
alias ls='ls --color=auto'
alias mkdir='nocorrect mkdir'
alias e="emacsclient -nc"
alias ec="emacsclient -t"
alias en="emacsclient -n"
alias eckill="emacsclient -e '(kill-emacs)'"
alias tmux='tmux -2'
alias ack="ack-grep --pager=\"less -R\""

# generic env setting
export TERMINFO=/lib/terminfo	# required for gdb-tui
export TZ='Asia/Kolkata'; export TZ
export LC_ALL='en_US.UTF-8'
# export TERM=xterm-256color
[[ $TMUX = "" ]] && export TERM="xterm-256color"
export ALTERNATE_EDITOR=""
export EDITOR="emacsclient -t"
export GIT_EDITOR="emacsclient -t"
export MINICOM="-m -c on"	# start minicom in color

# make git enabled prompt themes faster
function __git_files {
  _wanted files expl 'local files' _files
}

# set the prompt
function _update_ps1()
{
 export PROMPT="$(~/powerline-zsh.py $?)"
}

precmd()
{
 _update_ps1
}

# zsh-manydots-magic
autoload -Uz manydots-magic
manydots-magic

# fasd initialization
eval "$(fasd --init auto)"
alias v='f -e vim'      # quick opening files with vim
alias m='f -e mplayer'  # quick opening files with mplayer
alias o='a -e xdg-open' # quick opening files with xdg-open
alias enn='f -e emacsclient -n'

# init autojump
[[ -s $HOME/.autojump/etc/profile.d/autojump.sh ]] && source $HOME/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u
export AUTOJUMP_IGNORE_CASE=1 # ignore case in autojump completion
export AUTOJUMP_AUTOCOMPLETE_CMDS='cp vim make'

# developement setup
alias cgdb-xilinx='cgdb -d arm-xilinx-linux-gnueabi-gdb -- -quiet'
export arm='ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi-'
export xilinx='ARCH=arm CROSS_COMPILE=arm-xilinx-linux-gnueabi-'

# freescale settings
alias cgdb_fscl='cgdb -d arm-linux-gnueabihf-gdb -- -quiet'
export fscl='ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-'

path=(
    /opt/Xilinx/SDK/2014.3.1/gnu/arm/lin/bin
    /opt/Xilinx/SDK/2014.3.1/bin
    /opt/arm-2014.05/bin
    /opt/gcc-linaro-arm-linux-gnueabihf-4.8-2014.04_linux/bin
    /opt/mgls/linux/bin
    $path
)

# End of File
